pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node:22.14-alpine
    command:
    - sleep
    args:
    - infinity
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  - name: trivy 
    image: aquasecurity/trivy:latest
    imagePullPolicy: IfNotPresent
    command: 
    - sleep
    args:
    - 9999999
    resources:
        requests:
        cpu: "250m"
        memory: "512Mi"
    limits:
        cpu: "512m"
        memory: "1024Mi"
  volumes:
  - name: docker-config
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
'''
        }
    }
    environment {
        CI = 'true'
        IMAGE_TAG = "${BUILD_NUMBER}"
        PIPELINE_NAME = "${env.JOB_NAME}"
        REACT_APP_API_URL = 'https://192.168.13.128:30444/'
    }
    stages {
        stage('Check npm and install git') {
            steps {
                container('node') {
                    sh 'npm --version'
                    sh 'apk add --no-cache git'
                }
            }
        }
        stage('Install jdk') {
            steps {
                container('node') {
                    sh '''
                        apk add --no-cache openjdk17
                        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
                        export PATH=$JAVA_HOME/bin:$PATH
                        java -version
                    '''
                }
            }
        }
        // stage('Checkout') {
        //     steps {
        //         container('node') {
        //             checkout scmGit(
        //                 branches: [[name: '*/main']],
        //                 userRemoteConfigs: [[
        //                     url: 'https://github.com/billgates00s/SmashShop.git',
        //                     credentialsId: 'githubtoken'
        //                 ]]
        //             )
        //         }
        //     }
        // }
        stage('Checkout') {
            steps {
        // Đưa ra ngoài container block để Jenkins xử lý mặc định
                checkout scmGit(
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/billgates00s/SmashShop.git',
                        credentialsId: 'github-token' 
                    ]]
                )
            }
        }

        stage('Build and Test') {
            parallel {
                stage('Build') {
                    steps {
                        container('node') {
                            dir('frontend') {
                                sh 'npm ci'
                            }
                        }
                    }
                }
                stage('Test') {
                    steps {
                        container('node') {
                            dir('frontend') {
                                sh 'npm test -- --coverage || true'
                            }
                        }
                    }
                }
            }
        }
        stage('Code Analysis') {
            parallel {
                // stage('SonarQube Scan') {
                //     environment {
                //         SONAR_AUTH_TOKEN = credentials('sonarqube-token')
                //         SCANNER_HOME = tool 'sonarqube'
                //     }
                //     steps {
                //         container('node') {
                //             dir('frontend'){
                //                 withSonarQubeEnv(installationName: 'sonarqube') {
                //                     sh """
                //                         $SCANNER_HOME/bin/sonar-scanner \
                //                         -Dsonar.projectKey=smash-shop-frontend-project \
                //                         -Dsonar.host.url=http://192.168.13.128:31000/ \
                //                         -Dsonar.login=$SONAR_AUTH_TOKEN
                //                     """
                //                 }
                //             }
                //         }
                //     }
                // }
                stage('SonarQube Scan') {
                    steps {
                        // Thêm retry để nếu timeout do mạng thì sẽ thử lại
                        retry(2) {
                            container('node') {
                                script {
                                    def scannerHome = tool 'sonarqube'
                                    dir('frontend') {
                                        withSonarQubeEnv(credentialsId: 'sonarqube-token', installationName: 'sonarqube') {
                                            sh """
                                                ${scannerHome}/bin/sonar-scanner \
                                                -Dsonar.projectKey=smash-shop-frontend-project \
                                                -Dsonar.sources=. \
                                                -Dsonar.host.url=http://192.168.13.128:31000/ \
                                            """
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                stage('Trivy Source Scan') {
                    steps {
                        container('trivy') {
                            dir('frontend') {
                                sh '''
                                    trivy fs --no-progress --severity MEDIUM,HIGH,CRITICAL \
                                    --scanners vuln,secret \
                                    --format table . > trivy-source.txt 2>&1
                                    cat trivy-source.txt
                                '''
                                sh '''
                                    CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-source.txt | head -1)
                                    if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
                                        echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
                                        exit 1
                                    else
                                        echo "✅ No critical vulnerabilities found."
                                    fi
                                '''
                            }
                        }
                    }
                }
            }
        }
        stage('Quality Gate') {
            steps {
                container('node') {
                    dir('frontend'){
                        timeout(activity: true, time: 5, unit: 'MINUTES') {
                            waitForQualityGate abortPipeline: true, credentialsId: 'sonarqube-token'
                        }
                    }
                }
            }
        }
        stage('Trivy Source Scan') {
            steps {
                container('trivy') {
                    dir('frontend') {
                        sh '''
                            trivy fs --no-progress --severity MEDIUM,HIGH,CRITICAL \
                            --scanners vuln,secret \
                            --format table . > trivy-source.txt 2>&1
                            cat trivy-source.txt
                        '''
                        sh '''
                            CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-source.txt | head -1)
                            if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
                                echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
                                exit 1
                            else
                                 echo "✅ No critical vulnerabilities found."
                            fi
                        '''
                    }
                }
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    dir('frontend'){
                        sh '''#!/busybox/sh
                            /kaniko/executor \
                              --context `pwd` \
                              --destination nhannh/smash-shop-frontend-image:$IMAGE_TAG \
                              --build-arg REACT_APP_API_URL=$REACT_APP_API_URL \
                              --cache=true
                        '''
                    }
                }
            }
        }
        stage('Trivy Image Scan') {
            steps {
              container('trivy'){
                  dir('frontend'){
                      script { // Thêm script block nếu muốn dùng biến Groovy
                        sh '''
                            trivy image --no-progress --severity MEDIUM,HIGH,CRITICAL \
                                        --scanners vuln,secret \
                                        --skip-files ".npm/_cacache" \
                                        --timeout 10m nhannh/smash-shop-frontend-image:$IMAGE_TAG > trivy-image.txt
                            cat trivy-image.txt
                        '''
                        sh '''
                            CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-image.txt | head -1)
                            if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
                                echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
                                exit 1
                            else
                                echo "✅ No critical vulnerabilities found."
                            fi
                        '''
                        }
                    }
                }
             }
        }
        // stage('Update Manifests') {
        //     steps {
        //         container('node') {
        //             withCredentials([string(credentialsId: 'githubtoken', variable: 'GIT_TOKEN')]) {
        //                 sh '''
        //                     set -e
        //                     rm -rf smash-shop-k8s-mainfest
        //                     git clone https://github.com/NHongCuong/smash-shop-k8s-mainfest.git
        //                     cd smash-shop-k8s-mainfest/k8s-manifests/frontend
        //                     sed -i.bak "s|nhannh/smash-shop-frontend-image:.*|nhannh/smash-shop-frontend-image:$IMAGE_TAG|" deployment.yaml
        //                     git config user.email "nguyenhongnhana2@gmail.com"
        //                     git config user.name "billgates00s"
        //                     git add deployment.yaml
        //                     git commit -m "Update image to nhannh/smash-shop-frontend:$IMAGE_TAG"
        //                     git push https://$GIT_TOKEN@github.com/NHongCuong/smash-shop-k8s-mainfest.git HEAD:main
        //                 '''
        //             }
        //         }
        //     }
        // }
        stage('Update Manifests') {
            steps {
                container('node') {
                    script {
                        // Kiểm tra xem Jenkins có thực sự lấy được Credential không
                        try {
                            withCredentials([string(credentialsId: 'githubtoken', variable: 'GIT_TOKEN')]) {
                                sh """
                                    set -e
                                    # Cài đặt git nếu là Alpine
                                    if ! command -v git >/dev/null; then apk add --no-cache git; fi

                                    rm -rf smash-shop-k8s-mainfest
                                    #git clone https://${GIT_TOKEN}@github.com/billgates00s/smash-shop-k8s-mainfest.git
                                    git clone https://github.com/billgates00s/smash-shop-k8s-mainfest.git
                                    cd smash-shop-k8s-mainfest/k8s-manifests/frontend

                                    # Cập nhật tag image
                                    sed -i.bak "s|nhannh/smash-shop-frontend-image:.*|nhannh/smash-shop-frontend-image:$IMAGE_TAG|" deployment.yaml

                                    git config user.email "nguyenhongnhana2@gmail.com"
                                    git config user.name "billgates00s"
                                    git add deployment.yaml

                                    if git diff --cached --quiet; then
                                        echo "No changes to commit"
                                    else
                                        #git commit -m "Update image to version ${IMAGE_TAG}"
                                        #git push origin main
                                        git commit -m "Update image to nhannh/smash-shop-frontend:$IMAGE_TAG"
                                        git push https://$GIT_TOKEN@github.com/billgates00s/smash-shop-k8s-mainfest.git HEAD:main
                                    fi
                                """
                            }
                        } catch (Exception e) {
                            error "Lỗi Credentials: Không tìm thấy ID 'githubtoken' trong Jenkins. Vui lòng kiểm tra lại Manage Jenkins > Credentials."
                        }
                    }
                }
            }
        }
        stage('Trigger ArgoCD Sync') {
            steps {
                container('node') {
                    withCredentials([string(credentialsId: 'argocd-token', variable: 'ARGOCD_TOKEN')]) {
                        sh '''
                            apk add --no-cache curl
                            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
                            install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
                            rm argocd-linux-amd64
                            #argocd login argocd-server.argocd.svc.cluster.local:443 --username admin --password $ARGOCD_TOKEN --insecure
                            #argocd app sync smash-shop-frontendargocd 
							argocd app sync smashshop-frontend \
                                --server argocd-server.argocd.svc.cluster.local:443 \
                                --auth-token ${ARGOCD_TOKEN} \
                                --insecure \
                                --prune
							
                         '''
                     }
                 }
             }
        }
    }
    post {
        always {
            echo "Pipeline '${PIPELINE_NAME}' completed."
        }
        success {
            emailext attachLog: true, 
                     body: "The pipeline '${PIPELINE_NAME} Build #${BUILD_NUMBER}' has completed successfully.", 
                     subject: "Pipeline Success: ${PIPELINE_NAME} - Build #${BUILD_NUMBER}", 
                     to: 'nhannh1013@gmail.com'
        }
        failure {
            emailext attachLog: true, 
                     body: "The pipeline '${PIPELINE_NAME}' has failed. Please review the attached logs.", 
                     subject: "Pipeline Failed: ${PIPELINE_NAME} - Build #${BUILD_NUMBER}", 
                     to: 'nhannh1013@gmail.com'
        }
    }
}