server {
    listen 80;
    # IP của máy chủ Ubuntu của bạn
    server_name 192.168.88.133; 

    root /usr/share/nginx/html;
    index index.html;

    # 1. Xử lý yêu cầu vào trang Web (Frontend)
    location / {
        # Sửa lại dòng này để hỗ trợ cả folder và file
        try_files $uri $uri/ /index.html;
    }

    # 2. Xử lý yêu cầu gọi dữ liệu (Backend)
    # QUAN TRỌNG: Đây là cầu nối giúp xóa lỗi 405 và liên kết Data
    location /api/ {
        # 'smashshop-backend-service' là tên Service Backend trong K8s của bạn
        proxy_pass http://smashshop-backend-service.application-deployment.svc.cluster.local;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        
        # Truyền IP thật của người dùng sang Backend
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Ép giữ nguyên phương thức POST/PUT để tránh lỗi 405
        proxy_method $request_method;
        
        # Xử lý vấn đề timeout nếu DB phản hồi chậm
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }
}